"""Build the app's icon fonts: Material Symbols subset to the icons we actually use.

Usage (needs `pip install fonttools`):  python scripts/build-icons.py

Add a name to ICONS (see https://fonts.google.com/icons), re-run, and use it as <Icon name="..." />.
Writes assets/fonts/ChalkIcons-{Regular,Filled}.ttf and src/components/icon-glyphs.ts.
"""
import json
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
NM = ROOT / 'node_modules'
SYMBOLS = NM / 'expo-symbols/build/android/symbols.json'
FONTS = {
    'Regular': NM / '@expo-google-fonts/material-symbols/400Regular/MaterialSymbols_400Regular.ttf',
    'Filled': NM / '@expo-google-fonts/material-symbols/400Regular_Filled/MaterialSymbols_400Regular_Filled.ttf',
}

ICONS = sorted({
    # navigation & chrome
    'arrow_back', 'close', 'settings', 'more_vert', 'chevron_right', 'expand_more', 'check', 'add', 'remove',
    # board & history
    'history', 'photo_library', 'grid_view', 'crop_square', 'swap_horiz', 'draw', 'edit', 'send',
    'reply', 'replay', 'delete', 'share', 'content_copy', 'image', 'photo_camera', 'text_fields', 'add_photo_alternate',
    # drawing tools
    'undo', 'redo', 'brush', 'ink_eraser', 'palette', 'add_reaction', 'wallpaper', 'stylus_pen',
    'stylus_highlighter', 'gesture', 'auto_awesome', 'flip_to_front', 'pan_tool',
    # together & profile
    'favorite', 'local_fire_department', 'mood', 'location_on', 'event', 'group', 'person_add',
    'quiz', 'forum', 'celebration', 'widgets', 'logout', 'lock', 'key', 'privacy_tip', 'mail',
    'notifications', 'schedule', 'refresh', 'visibility', 'visibility_off', 'hourglass_top',
})


def main():
    symbols = json.loads(SYMBOLS.read_text(encoding='utf-8'))
    missing = [n for n in ICONS if n not in symbols]
    if missing:
        raise SystemExit(f'Unknown icon names: {missing}')
    glyphs = {n: symbols[n] for n in ICONS}

    for style, src in FONTS.items():
        dest = ROOT / f'assets/fonts/ChalkIcons-{style}.ttf'
        font = TTFont(src)
        opts = subset.Options()
        opts.layout_features = []  # codepoints only; no ligatures needed
        opts.name_IDs = ['*']
        opts.notdef_outline = True
        sub = subset.Subsetter(opts)
        sub.populate(unicodes=list(glyphs.values()))
        sub.subset(font)
        # Unique family name so it can't clash with a system Material Symbols font.
        for rec in font['name'].names:
            if rec.nameID in (1, 4, 6, 16):
                rec.string = f'ChalkIcons-{style}' if rec.nameID == 6 else f'ChalkIcons {style}'
        font.save(dest)
        print(f'wrote {dest.relative_to(ROOT)} ({dest.stat().st_size // 1024} KB)')

    lines = [
        '// Generated by scripts/build-icons.py. Do not edit; add names there and re-run.',
        '',
        'export const ICON_GLYPHS = {',
        *[f"  {n}: '\\u{{{cp:x}}}'," for n, cp in glyphs.items()],
        '} as const;',
        '',
        'export type IconName = keyof typeof ICON_GLYPHS;',
        '',
    ]
    out = ROOT / 'src/components/icon-glyphs.ts'
    out.write_text('\n'.join(lines), encoding='utf-8')
    print(f'wrote {out.relative_to(ROOT)} ({len(glyphs)} icons)')


if __name__ == '__main__':
    main()
