-- Daily questions. audience: any | couple | group
insert into public.questions (body, category, audience) values
-- fun / any
('What''s a small thing that made you smile today?', 'fun', 'any'),
('If you could have dinner with anyone, alive or not, who would it be?', 'fun', 'any'),
('What''s the most useless talent you have?', 'fun', 'any'),
('Which fictional world would you most want to live in?', 'fun', 'any'),
('What''s your go-to karaoke song?', 'fun', 'any'),
('If you were a snack, what snack would you be?', 'fun', 'any'),
('What''s a food you could eat every day for a month?', 'fun', 'any'),
('Which superpower would you pick, and what''s the first thing you''d do with it?', 'fun', 'any'),
('What''s the weirdest dream you remember?', 'fun', 'any'),
('If your life had a theme song, what would it be?', 'fun', 'any'),
('What''s the best purchase you''ve made under $20?', 'fun', 'any'),
('What would your perfect lazy Sunday look like?', 'fun', 'any'),
('Which emoji do you use way too much?', 'fun', 'any'),
('If you could instantly master one skill, what would it be?', 'fun', 'any'),
('What''s a movie you could rewatch forever?', 'fun', 'any'),
('Describe your current mood as a weather forecast.', 'fun', 'any'),
('If animals could talk, which would be the rudest?', 'fun', 'any'),
('What''s the most spontaneous thing you''ve ever done?', 'fun', 'any'),
('Pineapple on pizza: defend your answer.', 'fun', 'any'),
('If you opened a tiny shop, what would it sell?', 'fun', 'any'),
('What song is stuck in your head right now?', 'fun', 'any'),
('What''s a trend you never understood?', 'fun', 'any'),
('If you could live in any decade, which would you choose?', 'fun', 'any'),
('What''s your comfort TV show?', 'fun', 'any'),
('What''s the best smell in the world?', 'fun', 'any'),
('If you won the lottery tomorrow, what''s the first thing you''d buy?', 'fun', 'any'),
('Which app on your phone do you use the most?', 'fun', 'any'),
('What''s your hottest hot take?', 'fun', 'any'),
('Morning person or night owl, and why?', 'fun', 'any'),
('What''s the last thing that made you laugh out loud?', 'fun', 'any'),
-- deep / any
('What''s something you''re proud of that you rarely talk about?', 'deep', 'any'),
('What does a perfect day look like for you, start to finish?', 'deep', 'any'),
('What''s a lesson you learned the hard way?', 'deep', 'any'),
('What''s one thing you wish more people knew about you?', 'deep', 'any'),
('When do you feel most like yourself?', 'deep', 'any'),
('What''s a fear you''ve overcome?', 'deep', 'any'),
('What''s something you''ve changed your mind about in the last year?', 'deep', 'any'),
('What''s a goal you''re quietly working towards?', 'deep', 'any'),
('What does home feel like to you?', 'deep', 'any'),
('What''s the kindest thing a stranger has done for you?', 'deep', 'any'),
('Which memory would you relive if you could?', 'deep', 'any'),
('What''s something you''re grateful for this week?', 'deep', 'any'),
('What advice would you give your younger self?', 'deep', 'any'),
('What''s a small habit that improved your life?', 'deep', 'any'),
('What does success mean to you right now?', 'deep', 'any'),
('Who has influenced you the most, and how?', 'deep', 'any'),
('What helps you recharge after a rough day?', 'deep', 'any'),
('What''s something you want to learn this year?', 'deep', 'any'),
('What''s a tradition you want to keep forever?', 'deep', 'any'),
('What are you looking forward to this month?', 'deep', 'any'),
-- couple
('What was your first impression of me?', 'us', 'couple'),
('When did you first realize you liked me?', 'us', 'couple'),
('What''s your favorite memory of us so far?', 'us', 'couple'),
('What''s something I do that always makes you feel loved?', 'us', 'couple'),
('Where should our next trip together be?', 'us', 'couple'),
('What''s a date idea we haven''t tried yet?', 'us', 'couple'),
('What song reminds you of us?', 'us', 'couple'),
('What''s one thing you''d love for us to do more often?', 'us', 'couple'),
('What''s a quirk of mine you secretly love?', 'us', 'couple'),
('Describe our relationship in three words.', 'us', 'couple'),
('What''s your favorite way to spend time with me?', 'us', 'couple'),
('What''s something you''ve learned from me?', 'us', 'couple'),
('What does your dream home with me look like?', 'us', 'couple'),
('What was the moment you felt closest to me?', 'us', 'couple'),
('What''s a goal you want us to achieve together?', 'us', 'couple'),
('Which of my outfits is your favorite?', 'us', 'couple'),
('What would our couple name be?', 'us', 'couple'),
('If we had a pet together, what would we name it?', 'us', 'couple'),
('What''s a small gesture from me you still think about?', 'us', 'couple'),
('What''s your favorite photo of us and why?', 'us', 'couple'),
('How do you like to be comforted when you''re sad?', 'us', 'couple'),
('What''s our funniest inside joke?', 'us', 'couple'),
('What''s something new you''d like to try together?', 'us', 'couple'),
('What made you laugh the hardest with me?', 'us', 'couple'),
('What''s one thing I could do this week to make your day better?', 'us', 'couple'),
('Which love language speaks to you the most right now?', 'us', 'couple'),
('Where do you see us in five years?', 'us', 'couple'),
('What''s the best meal we''ve shared?', 'us', 'couple'),
('If we wrote a book about us, what would the title be?', 'us', 'couple'),
('What''s a tiny everyday moment with me you love?', 'us', 'couple'),
-- group / friends
('Who in this group would survive the longest in a zombie apocalypse?', 'squad', 'group'),
('What''s your favorite memory with this group?', 'squad', 'group'),
('Who in the group is most likely to become famous?', 'squad', 'group'),
('What should our next group hangout be?', 'squad', 'group'),
('Which group member would you trust with your phone unlocked?', 'squad', 'group'),
('If our group was a TV show, what genre would it be?', 'squad', 'group'),
('Who is the group''s mom/dad friend?', 'squad', 'group'),
('What''s a group trip we absolutely need to take?', 'squad', 'group'),
('Who would win in a cooking competition here?', 'squad', 'group'),
('What''s the most chaotic thing that''s happened in this group?', 'squad', 'group'),
('Assign everyone in the group a spirit animal.', 'squad', 'group'),
('What''s a tradition this group should start?', 'squad', 'group'),
('Who in the group gives the best advice?', 'squad', 'group'),
('What song should be our group anthem?', 'squad', 'group'),
('Who is most likely to be late to their own wedding?', 'squad', 'group');

insert into public.tot_prompts (option_a, option_b) values
('Beach', 'Mountains'), ('Coffee', 'Tea'), ('Cats', 'Dogs'), ('Sunrise', 'Sunset'),
('Pizza', 'Burgers'), ('Movies at home', 'Cinema'), ('Sweet', 'Savory'), ('Summer', 'Winter'),
('Books', 'Podcasts'), ('City break', 'Road trip'), ('Early bird', 'Night owl'), ('Texting', 'Calling'),
('Rain', 'Sunshine'), ('Chocolate', 'Vanilla'), ('Pancakes', 'Waffles'), ('Netflix', 'YouTube'),
('Cook at home', 'Order in'), ('Flying', 'Invisibility'), ('Past', 'Future'), ('Board games', 'Video games'),
('Hoodie', 'Sweater'), ('Spicy', 'Mild'), ('Concert', 'Festival'), ('Fries', 'Onion rings'),
('Big party', 'Small hangout'), ('Camping', 'Hotel'), ('Plan everything', 'Go with the flow'), ('Ice cream', 'Cake'),
('Sneakers', 'Boots'), ('Horror', 'Comedy'), ('Sushi', 'Tacos'), ('Snow day', 'Beach day'),
('Bath', 'Shower'), ('Window seat', 'Aisle seat'), ('Breakfast', 'Dinner'), ('Gym', 'Yoga'),
('Messy bun', 'Fresh haircut'), ('Lake', 'Ocean'), ('Spring', 'Autumn'), ('Museum', 'Theme park'),
('Fruit', 'Candy'), ('Long walks', 'Long drives'), ('Handwritten letter', 'Surprise gift'), ('Dance', 'Sing'),
('Morning cuddles', 'Late-night talks'), ('Matching outfits', 'Never'), ('Surprise party', 'Quiet birthday'), ('Pasta', 'Rice'),
('Stars', 'City lights'), ('Picnic', 'Fancy dinner'), ('Croissant', 'Bagel'), ('Fantasy', 'Sci-fi'),
('Lemonade', 'Iced tea'), ('Mountains hike', 'Beach nap'), ('Pajama day', 'Adventure day'), ('Text first', 'Wait for them'),
('Popcorn', 'Nachos'), ('Old songs', 'New songs'), ('Train', 'Plane'), ('Thunderstorm', 'Snowfall'),
('Hot chocolate', 'Milkshake'), ('Paint', 'Write'), ('Teleport', 'Time travel'), ('Ten small trips', 'One huge trip'),
('Cozy cabin', 'Beach villa'), ('Strawberries', 'Watermelon'), ('Puzzle', 'Lego'), ('Karaoke', 'Bowling'),
('Socks on', 'Socks off'), ('Rom-com', 'Action'), ('Dumplings', 'Noodles'), ('Cheesecake', 'Brownies');
